server:
  compression:
    enabled: true
    min-response-size: 1KB
  shutdown: graceful
---
spring:
  application:
    name: api-gateway
---
management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: env, info
---
spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: '*'
                allowed-methods: GET, POST, PUT, DELETE, OPTIONS
                allowed-headers: '*'
                allow-credentials: false
          routes:
            - id: tinyurl-service
              uri: ${TINYURL_SERVICE_URI:http://localhost:8090}
              predicates:
                - Path=/tinyurl/**
              filters:
                - RewritePath=/tinyurl/(?<segment>.*), /${segment}
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URI:http://localhost:4567}
              predicates:
                - Path=/catalog/**
              filters:
                - RewritePath=/catalog/(?<segment>.*), /${segment}
            - id: ads-service
              uri: ${AD_SERVICE_URI:http://localhost:4568}
              predicates:
                - Path=/ads/**
              filters:
                - RewritePath=/ads/(?<segment>.*), /${segment}
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
---
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    version: openapi_3_1
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: catalog-service
        url: ${CATALOG_SERVICE_URI:http://localhost:4567}/v3/api-docs
      - name: ads-service
        url: ${AD_SERVICE_URI:http://localhost:4568}/swagger/ads-1.0.0.yml
    syntax-highlight:
      activated: true
      theme: dark
