services:
  redis:
    image: 'redis/redis-stack:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: on-failure

  catalog_db:
    image: 'mongo:latest'
    container_name: catalog_db
    environment:
      - 'MONGO_INITDB_DATABASE=catalog_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    restart: on-failure

  ads_db:
    image: 'mysql:latest'
    container_name: 'ads_db'
    environment:
      - 'MYSQL_DATABASE=ads_db'
      - 'MYSQL_PASSWORD=ads'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=ads'
    ports:
      - '3308:3306'
    restart: on-failure

  auth_db:
    image: 'postgres:latest'
    container_name: 'auth_db'
    environment:
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    restart: on-failure
