apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ads"
spec:
  selector:
    matchLabels:
      app: "ads"
  template:
    metadata:
      labels:
        app: "ads"
    spec:
      containers:
        - name: "ads"
          image: "gcr.io/ads/jib-image"
          ports:
            - name: http
              containerPort: 4568
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4568
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4568
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "ads"
spec:
  selector:
    app: "ads"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 4568
