name: Ads Service Build Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'src/ads/**'
      - '.github/workflows/ads-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/ads/**'
      - '.github/workflows/ads-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ads
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: ./mvnw -B verify --file pom.xml -DskipTests
