name: Catalog Service Build Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'src/catalog/**'
      - '.github/workflows/catalog-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/catalog/**'
      - '.github/workflows/catalog-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/catalog
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: ./mvnw -B verify --file pom.xml -DskipTests
