name: Review Service Build Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'src/review/**'
      - '.github/workflows/review-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/review/**'
      - '.github/workflows/review-build.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/review
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4
    - name: Update Deps
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
