name: TinyUrl Service Build Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'src/tinyurl/**'
      - '.github/workflows/tinyurl-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/tinyurl/**'
      - '.github/workflows/tinyurl-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tinyurl
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: ./mvnw -B verify --file pom.xml -DskipTests
